name: ci

on: push

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install clang-format"
        run: |
          sudo apt update
          sudo apt install -y clang-format
      - name: "Run stylecheck"
        run: |
          clang-format -Werror --dry-run \
                src/*.cpp src/*.hpp \
                tests/*.cpp tests.*.hpp
          #clang-format -i src/*.cpp src/*.hpp tests/*.cpp tests.*.hpp > /dev/null 2>&1 || echo "Consider the following changes: " && git --no-pager diff && exit -1

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install dependencies"
        run: |
          export DEBIAN_FRONTEND="noninteractive"
          sudo apt update && apt install -y \
                cmake \
                build-essential \
                libeigen3-dev \
                libyaml-cpp-dev \
                libboost-all-dev
      - name: "Build ..."
        run: |
          mkdir -p build && cd build
          cmake .. && make -j4 && cd ..
          tar -czvf build.tar.gz build
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: build.tar.gz
          retention-days: 3

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: build
      - name: "Testing ..."
        run : |
          tar -xvf build.tar.gz
          make test


