name: CI

on: push

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install clang-format"
        run: |
          sudo apt update
          sudo apt install -y clang-format
      - name: "Run stylecheck"
        run: |
        clang-format --dry-run src/* tests/*
        clang-format -i src/* tests/* > /dev/null 2>&1 || echo "Consider the following changes: " && git --no-pager diff && >&2 echo ""
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install dependencies"
        run: |
          export DEBIAN_FRONTEND="noninteractive"
          sudo apt update
          sudo apt install -y cmake build-essential libeigen3-dev
          sudo apt install -y libyaml-cpp-dev
          sudo apt install -y libboost-all-dev
      - name: "Build..."
        run: |
          mkdir -p build && cd build
          cmake .. && make -j4 && cd ..
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./build
          retention-days: 7

  # test:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   env:
  #     PROJECT_NAME: "Automation Lecture"
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: "Download coverage report (artifact)"
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: coverage
  #
  #     - name: "Upload coverage report (XML) (artifact)"
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: coverage-xml
  #         path: coverage.xml
  #         retention-days: 14

