name:

on: push


jobs:
#   style:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-python@v2
#       - name: "Install dependencies"
#         run: |
#           apt update
#           apt install
#           apt install -y clang-format
#           export DEBIAN_FRONTEND="noninteractive"
#           apt-get update && apt-get install -y apt-utils curl wget cmake build-essential
#           apt-get install -y libboost-filesystem-dev libboost-container-dev
#
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install dependencies"
        run: |
          export DEBIAN_FRONTEND="noninteractive"
          apt update
          apt install -y cmake build-essential
          apt install -y libeigen3-dev
          apt install -y libyaml-cpp-dev
      - name: "Install boost "
        run: |
          # apt install -y libboost-all-dev
          echo "##################\n\tDownloading latest boost version"
          wget https://sourceforge.net/projects/boost/files/boost/1.81.0/boost_1_81_0.tar.gz/download
          tar xzvf boost_1_81_0.tar.gz
          cd boost_1_81_0/
          echo "##################\n\tBuilding/Installing boost"
          ./bootstrap.sh
          ./b2
          ./bjam install
          cd ..
      - name: "Build..."
        run: |
          mkdir -p build
          cd build
          cmake ..
          make -j
          cd ..
      - name: "Test..."
        run: |
          clang-format --dry-run src/*
          clang-format --dry-run test/*
      - name: "Upload build"
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./build/
          retention-days: 7

  # test:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   env:
  #     PROJECT_NAME: "Automation Lecture"
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: "Download coverage report (artifact)"
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: coverage
  #
  #     - name: "Upload coverage report (XML) (artifact)"
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: coverage-xml
  #         path: coverage.xml
  #         retention-days: 14

